ONE = 1.0
TWO = 2.0
THREE = 3.0
FOUR = 4.0
FIVE= 5.0
SIX = 6.0
SEVEN = 7.0
EIGHT = 8.0
NINE = 9.0
TEN = 10.0

ELEVEN = ONE + TEN
TWELVE = ONE + ELEVEN
THIRTEEN = ONE + TWELVE
FOURTEEN = ONE + THIRTEEN
FIFTEEN = ONE + FOURTEEN
SIXTEEN = ONE + FIFTEEN
SEVENTEEN = ONE + SIXTEEN
EIGHTEEN = ONE + SEVENTEEN
NINETEEN = ONE + EIGHTEEN
TWENTY = ONE + NINETEEN

