ONE = 1
TWO = 2
THREE = 3
FOUR = 4
FIVE= 5
SIX = 6
SEVEN =7
EIGHT = 8
NINE = 9
TEN = 10

ELEVEN = ONE + TEN
TWELVE = ONE + ELEVEN
THIRTEEN = ONE + TWELVE
FOURTEEN = ONE + THIRTEEN
FIFTEEN = ONE + FOURTEEN
SIXTEEN = ONE + FIFTEEN
SEVENTEEN = ONE + SIXTEEN
EIGHTEEN = ONE + SEVENTEEN
NINETEEN = ONE + EIGHTEEN
TWENTY = ONE + NINETEEN

